FROM k8s-notebook

USER root

ADD start-elyra.sh /usr/local/bin/start-elyra.sh

RUN chmod ugo+x /usr/local/bin/start-elyra.sh && \
    apt-get update && apt-get install -y gcc g++ make libssl-dev libffi-dev python-dev gcc python3-dev python3-setuptools build-essential curl dirmngr apt-transport-https lsb-release ca-certificates &&\
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn && \
    rm -rf /var/lib/apt/lists/*

ENV PKG_CONFIG_PATH="/usr/lib/powerpc64le-linux-gnu/pkgconfig"
ENV LDFLAGS="-L/usr/lib/powerpc64le-linux-gnu"

USER $NB_USER

RUN python -m pip install --upgrade pip && \
    python -m pip install --ignore-installed --upgrade setuptools pandas && \
    echo "scripts-prepend-node-path=true" >> /home/jovyan/.npmrc && \
    echo "prefix=/home/jovyan/.npm-global" >> /home/jovyan/.npmrc && \
    mkdir -p /home/jovyan/.npm-global && \
    npm install -g yarn && \
    npm install -g npm
    
RUN conda install nodejs

#COPY ./elyra-1.1.0 /tmp/elyra
RUN cd /tmp && git clone https://github.com/elyra-ai/elyra.git && \
    cd /tmp/elyra && git checkout tags/v1.1.0 -b v1.1.0 && make install

RUN pip install "git+https://github.com/jupyter-incubator/nb2kg.git#egg=nb2kg"
RUN jupyter serverextension enable --py nb2kg --sys-prefix

# Run with remote kernel managers
CMD ["/usr/local/bin/start-nb2kg.sh"]

RUN jupyter serverextension list

# Add local files as late as possible to avoid cache busting
ADD jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
ADD start-nb2kg.sh /usr/local/bin/start-nb2kg.sh

USER $NB_USER

WORKDIR /home/jovyan/work

CMD ["/usr/local/bin/start-notebook.sh"]

